### PR TITLE
Doing a small cleanup

### PR DESCRIPTION
**Pull request by PeriGK**
Hi @liberodark ,

I just downloaded the code to have a look and decided to do a small clean up. :)

Could you please confirm something first? Is '// eslint-disable-line no-global-assign some kind of annotation? I havent seen the pattern before?

Cheers,
P.

### CODE REVIEW

**Comment by coyotte508** [comment]
```js
// eslint-disable-line no-global-assign
```
https://eslint.org/docs/rules/no-global-assign

This is to tell the tool we use to check the code that the line below is ok, and we know what we're doing.

**Comment by PeriGK** [comment]
Never said the opposite, I just wanted to verify. :)

**Comment by coyotte508** [comment]
Sorry if that came across wrong. I meant to say "We tell the tool we know what we're doing and to ignore..." :)

**Comment by liberodark** [comment]
great thank for your work :D

**Pull request merged**
