### PR TITLE
Tray information about sync status and storage use

### PR DESCRIPTION
**Pull request by no92**
This adds some information to the tray menu. The upper line displays the percentage of your storage quota used, as well as the storage quota itself, rounded to .1 GiB.

The line below displays the sync status. This is what it looks like in Ubuntu:
Drive

As this is my first time working with anything Electron-related, feel free to point out anything that is wrong with these changes.

### CODE REVIEW

**Comment by liberodark** [comment]
Good :D Thx

**Comment by liberodark** [comment]
Have see a bug the information is not good 
<a href="https://imgur.com/JC5Y4NU.png">
  
</a>

For 1 file add 4 info bulle :( please can you fix that ?

**Comment by liberodark** [comment]
Have merge in beta your pull request but in master have revert for fix bug please make other pr with no bug thanks ^^
And great job

**Comment by no92** [comment]
These changes should (as far as I can tell) only hook the routines in order to provide the info. It should not tamper with data (or notifications for that matter), but it might just be that something does things that I don't expect. I will investigate, but could you pin down conditions when this happens? I personally don't remember seeing issues before or after the changes ...

**Pull request merged**
